# Generated by Django 5.1.6 on 2025-03-01 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(help_text='Module Code (eg COMP1)', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='eg, Web services...', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(help_text='Professor ID (eg, JE1)', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Professor's full name, eg John Smith", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='eg 2018 for 2018-2019')),
                ('semester', models.IntegerField(help_text='Semester: 1 or 2', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='rating.module')),
                ('professors', models.ManyToManyField(help_text='Professor(s) teaching this module', related_name='moduleInstance', to='rating.professor')),
            ],
            options={
                'unique_together': {('module', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('moduleInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.moduleinstance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'moduleInstance', 'professor')},
            },
        ),
    ]
